spring:
  h2:
    console:
      enabled: true
      path: '/console'

  datasource:
    url: 'jdbc:h2:file:C:/Users/kamil/OneDrive/Pulpit/todo-appV2/todo-db'

  jpa:
    hibernate:
      ddl-auto: validate

management:
  endpoints:
    web:
      exposure:
        include: '*'
task.template.allowMultipleTasks: false